various changes to avoid a running into a hard assert
The device console log prior to applying these changes got:
...
I (17559) wifi:Deinit lldesc rx mblock:10
D (17563) nvs: nvs_close 2
D (17567) nvs: nvs_close 1
D (17568) esp_idf_svc::wifi: Driver deinitialized
D (17573) esp_idf_svc::wifi: WifiDriver Dropped
V (17577) pthread: pthread_mutex_destroy 0x3fca8cdc
I (17583) esp_idf_svc::nvs: NvsDefault dropped
D (17587) event: deleting loop 0x3fc9e08c
I (17592) esp_idf_svc::eventloop: System event loop dropped
V (17599) pthread: pthread_mutex_destroy 0x3fcad6d8
V (17602) pthread: pthread_mutex_destroy 0x3fcad4a0
V (17607) pthread: pthread_mutex_destroy 0x3fca8d30
V (17612) pthread: pthread_mutex_destroy 0x3fcad2c8
V (17617) pthread: pthread_mutex_destroy 0x3fcad670
V (17622) pthread: pthread_mutex_destroy 0x3fcad4d0
V (17627) pthread: pthread_mutex_destroy 0x3fcad548
V (17632) pthread: pthread_mutex_destroy 0x3fcad608
V (17637) pthread: pthread_mutex_destroy 0x3fcad358
V (17642) pthread: pthread_mutex_destroy 0x3fcacae0
V (17648) pthread: pthread_mutex_destroy 0x3fcac838
V (17652) pthread: pthread_mutex_destroy 0x3fcac7d0
Error: ESP_ERR_TIMEOUT
I (17659) main_task: Returned from app_main()
V (17664) pthread: pthread_mutex_destroy 0x3fc9d9f0

assert failed: heap_caps_free heap_caps.c:387 (heap != NULL && "free() target pointer is outside heap areas")
Core  0 register dump:
MEPC    : 0x403816ec  RA      : 0x4038563a  SP      : 0x3fc9d5a0  GP      : 0x3fc90800
0x403816ec - panic_abort
    at /home/being/.espressif/esp-idf/v5.1.3/components/esp_system/panic.c:472
0x4038563a - __ubsan_include
    at /home/being/.espressif/esp-idf/v5.1.3/components/esp_system/ubsan.c:313
0x3fc90800 - __global_pointer$
    at ??:??
TP      : 0x3fc528d4  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x00000001  S1      : 0x3fc9d72d  A0      : 0x3fc9d5f8  A1      : 0x3fc91ba1
A2      : 0x00000001  A3      : 0x00000029  A4      : 0x00000001  A5      : 0x3fc97000
0x3fc97000 - s_sm_valid_bitmap
    at ??:??
A6      : 0x7a797877  A7      : 0x76757473  S2      : 0x0000005a  S3      : 0x3fc9d5f8
S4      : 0x3fc9d5f8  S5      : 0x3c11a936  S6      : 0x00000000  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001801  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
0x40380001 - _vector_table
    at ??:??
MHARTID : 0x00000000

Stack memory:
3fc9d5a0: 0xa5a5a5a5 0xa5a5a5a5 0x3c11a98c 0x4038c222 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x3fc91ba0
0x4038c222 - esp_ptr_in_drom
    at /home/being/.espressif/esp-idf/v5.1.3/components/esp_hw_support/include/esp_memory_utils.h:301
3fc9d5c0: 0x00373833 0xa5a5a5a5 0x00000000 0x00000000 0xa5000000 0x3fc91ed8 0x3c11aa58 0x3fc922c4
0x3c11aa58 - __func__.4
    at ??:??
3fc9d5e0: 0x3c11a936 0x3fc91ee8 0x3fc9d5c0 0x3fc91eec 0x3c11a98c 0x3fc91ba0 0x65737361 0x66207472
3fc9d600: 0x656c6961 0x68203a64 0x5f706165 0x73706163 0x6572665f 0x65682065 0x635f7061 0x2e737061
3fc9d620: 0x38333a63 0x68282037 0x20706165 0x4e203d21 0x204c4c55 0x22202626 0x65657266 0x74202928
3fc9d640: 0x65677261 0x6f702074 0x65746e69 0x73692072 0x74756f20 0x65646973 0x61656820 0x72612070
3fc9d660: 0x22736165 0x00000029 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000009
3fc9d680: 0x00000000 0x3fc9db20 0x3fc970c0 0x40389c62 0x00000001 0x3fca8d30 0x3fc9db20 0x420630e4
0x40389c62 - multi_heap_free_impl
    at /home/being/.espressif/esp-idf/v5.1.3/components/heap/multi_heap.c:232
0x420630e4 - pthread_setspecific
    at /home/being/.espressif/esp-idf/v5.1.3/components/pthread/pthread_local_storage.c:226
3fc9d6a0: 0x3fc9d020 0x00000000 0x3fc9004c 0x3fc97000 0x3fc9d020 0x3fc9004c 0x00000000 0x420407f0
0x3fc9004c - std::sync::reentrant_lock::current_thread_unique_ptr::X::__getit::__KEY
    at ??:??
0x3fc97000 - s_sm_valid_bitmap
    at ??:??
0x3fc9004c - std::sync::reentrant_lock::current_thread_unique_ptr::X::__getit::__KEY
    at ??:??
0x420407f0 - std::sys::pal::unix::thread_local_key::set
    at /home/being/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/thread_local_key.rs:16
3fc9d6c0: 0x3fc528d4 0x00000000 0x00000000 0x3fc97000 0x3fc9d020 0x3fc92cb4 0x3fc9d07c 0x40381b06
0x3fc97000 - s_sm_valid_bitmap
    at ??:??
0x3fc92cb4 - xTasksWaitingTermination
    at ??:??
0x40381b06 - heap_caps_free
    at /home/being/.espressif/esp-idf/v5.1.3/components/heap/heap_caps.c:391
3fc9d6e0: 0x3fc9d020 0x3fc9004c 0x3fc9d07c 0x60043000 0x00000000 0x00000000 0x00000000 0x420d187e
0x3fc9004c - std::sync::reentrant_lock::current_thread_unique_ptr::X::__getit::__KEY
    at ??:??
0x420d187e - _reclaim_reent
    at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/reent/reent.c:90
3fc9d700: 0x3fc9d020 0x00000000 0x00000000 0x3fc97000 0x3fc9d020 0x3fc92cb4 0x3fc9d020 0x40386710
0x3fc97000 - s_sm_valid_bitmap
    at ??:??
0x3fc92cb4 - xTasksWaitingTermination
    at ??:??
0x40386710 - prvDeleteTCB
    at /home/being/.espressif/esp-idf/v5.1.3/components/freertos/FreeRTOS-Kernel/tasks.c:5049
3fc9d720: 0x00000000 0x3fc92cb4 0x3fc97000 0x403867c0 0x00000000 0x00000000 0x00000000 0x00000000
0x3fc92cb4 - xTasksWaitingTermination
    at ??:??
0x3fc97000 - s_sm_valid_bitmap
    at ??:??
0x403867c0 - prvCheckTasksWaitingTermination
    at /home/being/.espressif/esp-idf/v5.1.3/components/freertos/FreeRTOS-Kernel/tasks.c:4753
3fc9d740: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9d760: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000154 0x3fc9d110
3fc9d780: 0x3fc970d4 0x3fc92d0c 0x3fc92d0c 0x3fc9d77c 0x3fc92d04 0x00000019 0xa5a5a5a5 0xa5a5a5a5
0x3fc92d0c - pxReadyTasksLists
    at ??:??
0x3fc92d0c - pxReadyTasksLists
    at ??:??
0x3fc92d04 - pxReadyTasksLists
    at ??:??
3fc9d7a0: 0x3fc9d77c 0x00000000 0x00000000 0x3fc9d178 0x454c4449 0xa5a5a500 0xa5a5a5a5 0x00a5a5a5
3fc9d7c0: 0x00000000 0x3fc9d770 0x00000000 0x00000000 0x3fca8d30 0x42062eae 0x00000000 0x3fc977a4
0x42062eae - pthread_cleanup_thread_specific_data_callback
    at /home/being/.espressif/esp-idf/v5.1.3/components/pthread/pthread_local_storage.c:126
3fc9d7e0: 0x3fc9780c 0x3fc97874 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000
3fc9d800: 0x420d07f8 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
0x420d07f8 - _cleanup_r
    at /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/findfp.c:229
3fc9d820: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9d840: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9d860: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9d880: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9d8a0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc9d8c0: 0x00000000 0x00000000 0x00000000 0x3f000200 0x0000000c 0x094e000a 0x00000000 0x3fc9d9a8
3fc9d8e0: 0x00000054 0x00000000 0x3fc9d8e4 0x00000000 0x00000000 0x00000000 0x3fc9d8fc 0xffffffff
3fc9d900: 0x3fc9d8fc 0x3fc9d8fc 0x00000000 0x3fc9d910 0xffffffff 0x3fc9d910 0x3fc9d910 0x00000001
3fc9d920: 0x00000001 0x00000000 0xa500ffff 0x00000000 0xb33fffff 0x00000000 0x00000054 0x00000000
3fc9d940: 0x3fc9d93c 0x00000000 0x00000000 0x00000000 0x3fc9d954 0xffffffff 0x3fc9d954 0x3fc9d954
3fc9d960: 0x00000000 0x3fc9d968 0xffffffff 0x3fc9d968 0x3fc9d968 0x00000001 0x00000001 0x00000000
3fc9d980: 0xa500ffff 0x00000000 0xb33fffff 0x00000000 0x00000010 0x3fc92b34 0x3fc9d9b8 0x00000001
0x3fc92b34 - shutdown_handlers
    at ??:??



ELF file SHA256: 0000000000000000

Rebooting...
ESP-ROM:esp32c3-api1-20210207